_template: /home/src404/src/cper-codex
_src_path: /home/src404/src/cper-codex
project_name: "neuroctrl"
project_slug: "neuroctrl"
description: "Repo-backed Cognitive Control System"
author_name: ""
author_email: ""
domain_emphasis: "mixed"
